apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo 
  namespace: test-argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster:
              url: 'https://kubernetes.default.svc'
              environment: preproduction 
      - list:
          elements:
          - appName: podinfo
            namespace: podinfo
  template:
    metadata:
      name: '{{.appName}}-{{.cluster.environment}}'
      namespace: argocd
    spec:
      project: podinfo 
      source:
        repoURL: 'https://github.com/exzacter/project-harbinger.git'
        targetRevision: main
        path: 'core/helm/{{.appName}}'
        helm:
          releaseName: '{{.appName}}'
          valueFiles:
          - common.yaml
          - '{{.cluster.environment}}.yaml'
      destination:
        server: '{{.cluster.url}}' 
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - validate=true
