apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo 
  namespace: test-argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster:
              url: 'https://kubernetes.default.svc'
              environment: preproduction 
      - list:
          elements:
          - appName: podinfo
            namespace: podinfo
            revision: 6.5.4
            repoURL: 'https://stefanprodan.github.io/podinfo'
            chart: podinfo
  template:
    metadata:
      name: '{{.appName}}-{{.cluster.environment}}'
      namespace: argocd
    spec:
      project: podinfo 
      sources:
      - repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.revision}}'
        helm:
          releaseName: '{{.appName}}'
          valueFiles:
          - $values/core/helm/{{.appName}}/common.yaml
          - $values/core/helm/{{.appName}}/{{.cluster.environment}}.yaml
      - repoURL: https://github.com/exzacter/project-harbinger.git
        targetRevision: main
        ref: values
      destination:
        server: '{{.cluster.url}}' 
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - validate=true
