---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kite-route
  namespace: kite
spec:
  parentRefs:
  - name: eg 
    namespace: default
    sectionName: https
  hostnames:
  - "kite.dev.projectharbinger.xyz"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: kite
      port: 8080
