replicaCount: 1

image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: 6.5.4
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 9898

resources:
  limits:
    cpu: 100m
    memory: 93Mi
  requests:
    cpu: 50m
    memory: 54Mi
